name: End-to-end tests
on:
  push:
    branches:
      - '*'
  schedule:
    # 5 minutes
    - cron:  '*/3 * * * *'

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_BASE_URL: https://service.berlin.de
          CYPRESS_FROM_COUNTRY: Brazil
          CYPRESS_FM_FROM_UE: No
          CYPRESS_REQUEST_OPTION: "Residence permit to attend a language course (section 16f)"

          #Form data
          CYPRESS_FIRST_NAME: "Your First name"
          CYPRESS_LAST_NAME: "Your Last Name"
          CYPRESS_BIRTHDAY_DAY: 1
          CYPRESS_BIRTHDAY_MONTH: 2
          CYPRESS_BIRTHDAY_YEAR: 2000
          CYPRESS_EMAIL: your@email.com
          CYPRESS_NUMBER_OF_APPLICANTS: 1
          CYPRESS_HAS_RESIDENT_PERMITTED: No

      - name: Screenshots
        uses: actions/upload-artifact@v2
        with:
          path: cypress/screenshots/

      - name: Videos
        uses: actions/upload-artifact@v2
        with:
          path: cypress/videos/

        # If there is a file free-days.png, then it is mean that exist a appointment free, then github will fail and will be send an email!
      - name: Checking if there is an appointment available
        run: if [[ -f cypress/screenshots/language_course_appointment.js/free-days.png ]]; then ls broken_pipeline; fi
